# wrangler.toml のサンプル
name = "hono-tutorial"
main = "src/index.ts"
compatibility_date = "2025-02-01"
node_compat = true

# 以下、必要に応じて追加の設定を記述
# compatibility_flags = ["nodejs_compat"]

# vars など他の設定も同様に記述可能 

# 以下、オプション設定（必要に応じてコメントを外して有効化）:

# compatibility_flags = ["nodejs_compat"]

[vars]
DATABASE_URL = "postgresql://japonmaster:password@localhost:5600/questory"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "MY_DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1 